services:
  backend:
    image: portfolio-projects-api:latest
    container_name: portfolio-projects-api
#    ports:
#      - "8080:8080"
    networks:
      - portfolio
    environment:
      - spring_profiles_active=prod
networks:
    portfolio:
        external: true