services:
  backend:
    image: portfolio-projects-api:latest
    container_name: portfolio-projects-api
#    ports:
#      - "8080:8080"
    networks:
      - xcaddy
    environment:
      - spring_profiles_active=prod
networks:
  xcaddy:
    external: true